services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  classification:
    build: .
    image: dguilliams3/sentiment-escalation-engine-classification
    command: python run_classification.py
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  escalation:
    build: .
    image: dguilliams3/sentiment-escalation-engine-escalation
    command: python run_smart_escalation.py
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  ingest_api:
    build: .
    image: dguilliams3/sentiment-escalation-engine-ingest-api
    command: python submit_review.py
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
